#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper-Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

# +------------------------------------------+
# | VARIABLES                                |
# +------------------------------------------+
export TERM=vt100
if [ ! -f ntp-server-profile ]; then
   echo
   echo " +-------------------------------------------+"
   echo " |  No profile file found in this directory  |"
   echo " +-------------------------------------------+"
   echo
   exit
else
   source ntp-server-profile
fi

# patch system
if [ ! -f /etc/yum.repos.d/hopper.repo ]; then
   ./patch-client
fi

# NTP
source profile

yum install -y ntp
if [ x${ENABLE_NTP} == xTrue ]; then
   echo "" > /etc/ntp.conf
   echo "driftfile /var/lib/ntp/drift" >> /etc/ntp.conf
   echo "" >> /etc/ntp.conf
   echo "# restrict 10.14.1.0 mask 255.255.255.0 nomodify notrap" >> /etc/ntp.conf
   echo "" >> /etc/ntp.conf
   echo "server  127.127.1.0 # local clock" >> /etc/ntp.conf
   echo "server 0.rhel.pool.ntp.org iburst" >> /etc/ntp.conf
   echo "server 1.rhel.pool.ntp.org iburst" >> /etc/ntp.conf
   echo "" >> /etc/ntp.conf
   echo "fudge   127.127.1.0 stratum 10" >> /etc/ntp.conf
   echo "" >> /etc/ntp.conf
fi

# firewall
systemctl mask firewalld
systemctl stop firewalld
yum install -y iptables-services
systemctl stop  iptables
systemctl disable iptables
sed -i 's/enforcing/disabled/g' /etc/selinux/config
echo 0 > /sys/fs/selinux/enforce

# update NTP
ntpdate -u pool.ntp.org
systemctl enable ntpd.service
systemctl restart ntpd.service
sleep 10

