#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper-Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

# +------------------------------------------+
# | VARIABLES                                |
# +------------------------------------------+
if [ ! -f gluster-volume-profile ]; then
   echo
   echo " +---------------------------------------------------------+"
   echo " |  No gluster-volume-profile file found in this directory |"
   echo " +---------------------------------------------------------+"
   echo
   exit
else
   source gluster-volume-profile
fi
cd $installdir

yum -y install glusterfs-server
systemctl restart glusterd

# +------------------------------------------+
# | CINDER                                   |
# +------------------------------------------+
repcount=`cat $installdir/gluster-volume-profile | grep CINDER_DISK | wc -l`
echo "gluster volume create $CINDER_VOL rep $repcount transport tcp \\" > /tmp/glusterbuild

declare -a arr1=(`cat $installdir/gluster-volume-profile | grep CINDER_DISK | awk -F= '{print $2}'`)
for i in ${arr1[@]}; do
   echo "${i} \\" >> /tmp/glusterbuild
done

echo "force" >> /tmp/glusterbuild
chmod 755 /tmp/glusterbuild

declare -a arr1=(`cat $installdir/gluster-volume-profile | grep OTHER_GLUSTER_NODE | awk -F= '{print $2}'`)
for i in ${arr1[@]}; do
   gluster peer probe $i
   sleep 1
done
sleep 10

echo y > /tmp/yes
/tmp/glusterbuild < /tmp/yes
sleep 1
gluster volume start $CINDER_VOL
sleep 1

gluster peer status
gluster pool list
gluster volume status
gluster volume info

# gluster configuration
gluster volume set cindervol01 storage.owner-uid 165
gluster volume set cindervol01 storage.owner-gid 165
gluster volume set cindervol01 server.allow-insecure on

gluster volume stop $CINDER_VOL < /tmp/yes
rm -f /tmp/glusterbuild /tmp/yes

# allow IP range
NETW=`cat $installdir/gluster-volume-profile | grep CINDER_DISK | awk -F= '{print $2}' | cut -d"." -f1-3 | sort | uniq`
gluster volume set $CINDER_VOL auth.allow $NETW.*

# heartbeat ping
echo "setting netping to $NETPING seconds..."
source $installdir/gluster-volume-profile
gluster volume set $CINDER_VOL network.ping-timeout $NETPING
gluster volume start $CINDER_VOL

echo "End gluster-volume"
