#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper-Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

# source configuration file
NAGIOS=False                    # unless overridden
if [ ! -f novaboot-volume-profile ]; then
   echo
   echo "No novaboot-volume-profile file found in current directory"
   echo
   exit
else
   source novaboot-volume-profile
fi
cd $installdir

# install gluster
yum -y install glusterfs-server
systemctl restart glusterd


# +----------------------------------------+
# |                 NOVABOOT               |
# +----------------------------------------+
repcount=`cat novaboot-volume-profile | grep ^NOVABOOT_DISK | wc -l`
echo "gluster volume create $NOVABOOT_VOL rep $repcount transport tcp \\" > /tmp/glusterbuild

declare -a arr1=(`cat novaboot-volume-profile | grep ^NOVABOOT_DISK | awk -F= '{print $2}'`)
for i in ${arr1[@]}; do
   echo "${i} \\" >> /tmp/glusterbuild
done

echo "force" >> /tmp/glusterbuild
chmod 755 /tmp/glusterbuild

declare -a arr1=(`cat novaboot-volume-profile | grep ^OTHER_NOVABOOT_NODE | awk -F= '{print $2}'`)
for i in ${arr1[@]}; do
   gluster peer probe $i
done
sleep 1

echo y > /tmp/yes
/tmp/glusterbuild < /tmp/yes
sleep 1
gluster volume start $NOVABOOT_VOL
sleep 1

gluster peer status
gluster pool list
gluster volume status
gluster volume info

# additional gluster configuration
gluster volume set $NOVABOOT_VOL storage.owner-uid 165
gluster volume set $NOVABOOT_VOL storage.owner-gid 165
gluster volume set $NOVABOOT_VOL server.allow-insecure on

gluster volume stop $NOVABOOT_VOL < /tmp/yes
rm -f /tmp/glusterbuild /tmp/yes

# secure which ip range can see the gluster filesystem
# management VM network enabled
NETW=`cat novaboot-volume-profile | grep ^NOVABOOT_DISK | awk -F= '{print $2}' | cut -d"." -f1-3 | sort | uniq`

# set the network ping to determine when other node is down
# default value is 42 seconds - 5 seconds is for testing only
echo "setting netping to $NOVANETPING seconds..."
source novaboot-volume-profile
gluster volume set $NOVABOOT_VOL network.ping-timeout $NOVANETPING
gluster volume start $NOVABOOT_VOL

echo "End novaboot-volume"

