#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper-Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

if [ ! -f freeipa-server-config ]; then
   echo
   echo "No nagios-server-config file found in current directory"
   echo
   exit
else
   source freeipa-server-config
fi

if [ x$ENABLE_ETCHOSTS == xTrue ]; then
   check=`cat /etc/hosts | grep Hopper | awk '{print $1}'`
   if [ x$check == x ]; then
      cat hosts-file >> /etc/hosts
   fi
fi

# install hopper.repo
if [ ! -f /etc/yum.repos.d/hopper.repo ]; then
   ./yumclient
else
   yum --enablerepo=hopper clean metadata > /dev/null 2>&1
fi

#  disable firewall services
# ---------------------------
systemctl mask firewalld
systemctl stop firewalld
yum -y install iptables-services
systemctl stop  iptables
systemctl disable iptables
sed -i 's/enforcing/disabled/g' /etc/selinux/config
echo 0 > /sys/fs/selinux/enforce

#  install NTP
# -------------
yum -y install ntp
systemctl enable ntpd.service
if [ x$NTPCONFIG != xNone ]; then
   sed -i "/server 0/i server $NTPCONFIG" /etc/ntp.conf
   systemctl restart ntpd.service
   sleep 5
   ntpdate -u $NTPCONFIG
fi


# -----------------------------------------------------
#                       PACKAGES
# -----------------------------------------------------

yum install -y ipa-server
yum install -y bind-dyndb-ldap
yum install -y bind-pkcs11

echo "no" > /tmp/yes
echo "$FREEIPAHN.$DNSDOMAIN" >> /tmp/yes
echo "$FREEIPAIP" >> /tmp/yes
echo "$FREEIPAREALM" >> /tmp/yes
echo "$DIRMANGRASS" >> /tmp/yes
echo "$DIRMANGRASS" >> /tmp/yes
echo "$IPAADMINPASS" >> /tmp/yes
echo "$IPAADMINPASS" >> /tmp/yes
echo "yes" >> /tmp/yes

ipa-server-install < /tmp/yes

firewall-cmd --permanent --add-service=ntp
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-service=ldap
firewall-cmd --permanent --add-service=ldaps
firewall-cmd --permanent --add-service=kerberos
firewall-cmd --permanent --add-service=kpasswd

authconfig --enablemkhomedir --update
chkconfig sssd on
init 6



