#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper-Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

# source configuration file
export TERM=vt100
if [ ! -f profile ]; then
   echo
   echo "No profile file found in current directory"
   echo
   exit
else
   source profile
fi

cd /opt
wget -nv http://$FILESERVER/$HTTPFILES/s3cmd/master.zip
unzip master.zip
rm -f master.zip

DIR=/opt/s3cmd-master
cd $DIR
DATE=`date +"%a_%b-%d-%Y"`
ALLDB=complete-${DATE}.sql

echo $S3ACCESSKEY > /tmp/s3
echo $S3SECRETKEY >> /tmp/s3
echo $S3REGION >> /tmp/s3
echo $S3ENCRYPTPWD >> /tmp/s3
echo "/usr/bin/gpg" >> /tmp/s3
echo "Yes" >> /tmp/s3

if [ x$SQUID_ENABLED == xTrue ]; then
   echo "$SQDSERVHN" >> /tmp/s3
else
   echo "" >> /tmp/s3
fi

echo "Y" >> /tmp/s3
echo "y" >> /tmp/s3

$DIR/s3cmd --configure < /tmp/s3
rm -f /tmp/s3

CMD=`$DIR/s3cmd ls s3://${S3POD} 2>&1| head -1 | awk '{print $1}'`
if [ x$CMD == xERROR: ]; then
   $DIR/s3cmd mb s3://${S3POD}
fi

FILE=/var/mariadb-backup/mariadb-backup.sh

echo "CKCOM=\`$DIR/s3cmd ls s3://${S3POD}/\$ALLDB | head -1 | awk '{print \$1}'\`" >> $FILE
echo "if [ x\$CKCOM == x ]; then" >> $FILE
echo "   # S3 backup" >> $FILE
echo "   # ---------" >> $FILE
echo "   S3POD=$S3POD" >> $FILE
echo "   $DIR/s3cmd put /var/log/mariadb-backup/*-$DATE.sql.gz s3://${S3POD}" >> $FILE
echo "fi" >> $FILE

echo "DBS=/var/log/mariadb-backup" >> $FILE
echo "DAYS=+7" >> $FILE

echo "find \$DBS -ctime \${DAYS} -type f | cut -f5 -d/ | \\" >> $FILE
echo "awk -v var=\${S3POD} -v dir=\${DIR} '{print dir\"/s3cmd del s3://\"var\"/\"\$1}' > /tmp/del-s3" >> $FILE
echo "chmod 755 /tmp/del-s3; /tmp/del-s3" >> $FILE
echo "" >> $FILE

